#!/bin/bash
set -euo pipefail
cd $(dirname $0)/..

IMAGE_NAME=web-ui:dev
 
docker build -t ${IMAGE_NAME} .
docker run \
  -it \
  --rm \
  --name web-ui \
  -v $(pwd):/app \
  -v /app/node_modules \
  -p 3000:3000 \
  -e CHOKIDAR_USEPOLLING=true ${IMAGE_NAME} \
